# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_auto_20170806_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='question_number',
            new_name='question',
        ),
    ]
