# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_auto_20170806_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
