# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0005_auto_20170806_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='question',
            new_name='question_number',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
